services:
  db:
    container_name: recipe-app-postgres-database
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'