name: Maven CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPOSITORY: ghcr.io/MikeBenton2/ABNRecipeAPI
      BUILD_PATH: ./target

    steps:
      - name: Step 1 - Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Step 2 - Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Step 3 - Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Step 4 - Build Project with Maven
        run: ./mvnw -B -DskipTests package --file pom.xml

      - name: Step 5 - Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Step 6 - Build Images and Publish to Github
        run: |
          chmod +x AppBuild.sh && ./AppBuild.sh false ${{ github.run_number }}
          docker push ${{ env.IMAGE_REPOSITORY }}/abn-app:${{ github.run_number }}